#!/bin/bash
# Human SIRT2 Histone Deacetylase (PDB Entry 1J8F // https://www.rcsb.org/structure/1J8F)
# Fetch protein sequence from the FASTA file (utilizing one monomer for demonstration simplicity)

# Define constants
config_filename="ex_1J8F_cli.json"
job_name="ex_1J8F_cli_job"

# Protein sequence for SIRT2 monomer
protein_sequence="\
GEADMDFLRNLFSQTLSLGSQKERLLDELTLEGVARYMQSERCRRVICLVGAGISTSAGIPDFRSPSTGLYDNLEKYHLPYPEAIFEISYFKKHPEPFFALAKELYPGQFKPTICHYFM\
RLLKDKGLLLRCYTQNIDTLERIAGLEQEDLVEAHGTFYTSHCVSASCRHEYPLSWMKEKIFSEVTPKCEDCQSLVKPDIVFFGESLPARFFSCMQSDFLKVDLLLVMGTSLQVQPFAS\
LISKAPLSTPRLLINKEKAGQSDPFLGMIMGLGGGMDFDSKKAYRDVAWLGECDQGCLALAELLGWKKELEDLVRREHASIDAQS\
\
"

# One associated Zinc Ion per SIRT2 monomer
zinc_ion_smile="[Zn2+]"

# Run the command to configure and add protein/ligand data
python -m af3cli config --filename "$config_filename" --jobname "$job_name" \
  - protein add --sequence "$protein_sequence" \
  - ligand add --smiles "$zinc_ion_smile"

echo "The example input file '$config_filename' has been generated successfully."
