#!/bin/bash

# Absolute filepaths to FASTA files
filepath_protein="$(realpath "$(dirname "${BASH_SOURCE[0]}")")/complex_sys_integrase.fasta"
filepath_dna="$(realpath "$(dirname "${BASH_SOURCE[0]}")")/complex_sys_vDNA.fasta"

# Run the CLI command
af3cli config --filename "complex_system_recalc.json" --jobname "complex_system_recalc_job" \
  - protein add --fasta True --sequence ${filepath_protein} -n 8 \
  - dna add --fasta True --sequence ${filepath_dna} --complement -n 2 \
  - ligand add --ccd "DLU" --num 8 \
  - ligand add --ccd "MG" --num 16 \
  - ligand add --ccd "ZN" --num 8 \
  - debug --show  # Exclude this line to enable .json file creation



