#!/bin/bash

# Example
# Structure of MAP2K1 (MEK1) in complex with 5Z7-oxozeaenol
# Details:
# - Protein Data Bank (PDB) Entry: 8YP4
# - Reference: https://www.rcsb.org/structure/8YP4

# Define filename and job name
FILENAME="paper_covalent_bond_cli.json"
JOB_NAME="paper_covalent_bond_cli_job"

# Protein sequence for MEK1
PROTEIN_SEQUENCE="\
MQKKLEELELDEQQRKRLEAFLTQKQKVGELKDDDFEKISELGAGNGGVVFKVSHKPSGLVMARKLIHLEIKP\
AIRNQIIRELQVLHECNSPYIVGFYGAFYSDGEISICMEHMDGGSLDQVLKKAGRIPEQILGKVSIAVIKGLT\
YLREKHKIMHRDVKPSNILVNSRGEIKLCDFGVSGQLIDSMANSFVGTRSYMSPERLQGTHYSVQSDIWSMGL\
SLVEMAVGRYPIPPPDAKELELMFGCQVEGDAAEAPPRPRAPGRPLASYGMDSRPPMAIFELLDYIVNEPPPK\
LPSGVFSLEFQDFVNKCLIKNPAERADLKQLMVHAFIKRSDAEEVDFAGWLCSTIGLNQPSTAAALEHHHHHH\
"
PROTEIN_ID="A"
RESIDUE_POSITION=175
RESIDUE_BOND_ATOM_ID="SG"


# Ligand 5Z7-oxozeaenol
LIGAND_CCD="WNT"
LIGAND_ID="B"
LIGAND_POSITION=1
LIGAND_BOND_ATOM_ID="C14"

# Bond expression
BOND_EXPRESSION="\
${LIGAND_ID}:${LIGAND_POSITION}:${LIGAND_BOND_ATOM_ID}-\
${PROTEIN_ID}:${RESIDUE_POSITION}:${RESIDUE_BOND_ATOM_ID}\
"


# Run the CLI command
af3cli config --filename "${FILENAME}" --jobname "${JOB_NAME}" \
  - ccd --filename "/home/doepnerp/Projekte/Development/local/af3cli_paper/components.cif" \
  - protein add --sequence "${PROTEIN_SEQUENCE}" -i ${PROTEIN_ID} \
  - ligand add --ccd ${LIGAND_CCD} -i ${LIGAND_ID} \
  - bond --add ${BOND_EXPRESSION} #\
#  - debug --show  # Exclude this line to enable .json file creation
