#!/bin/bash

# Example
# Insulin dimer with water molecules
# Details:
# - Protein Data Bank (PDB) Entry: 1ZNI
# - Reference: https://www.rcsb.org/structure/1ZNI

# Define filename and job name
FILENAME="paper_insulin_dimer_water_cli.json"
JOB_NAME="paper_insulin_dimer_water_cli_job"

# Sequence entries

## Protein entries
CHAIN_A="\
GIVEQCCTSICSLYQLENYCN\
"
CHAIN_B="\
FVNQHLCGSHLVEALYLVCGERGFFYTPKA\
"

CHAIN_NUM=2

# Water molecules
WATER="O"
WATER_NUM=96

# Run the CLI command
af3cli config --filename "${FILENAME}" --jobname "${JOB_NAME}" \
  - protein add --sequence "${CHAIN_A}" --num ${CHAIN_NUM} \
  - protein add --sequence "${CHAIN_B}" --num ${CHAIN_NUM} \
  - ligand add --smiles ${WATER} --num ${WATER_NUM} #\
#  - debug --show  # Exclude this line to enable .json file creation
